[package]
name = "postgres_backup_wal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
clap = "3.0.0-beta.4"